# Generated by Django 4.2.19 on 2025-02-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_isblocked'),
        ('blogapp', '0003_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blogapp.blog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ACCOUNT_BLOCKED', 'Account Blocked'), ('POST_BLOCKED', 'Post Blocked'), ('GENERAL_ALERT', 'General Alert')], default='GENERAL_ALERT', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='accounts.userprofile'),
        ),
    ]
