# Generated by Django 4.2.19 on 2025-02-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_notification_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reason',
        ),
    ]
