# Generated by Django 4.2.18 on 2025-02-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_username_logintable_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='first_name',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logintable',
            name='last_name',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
