# Generated by Django 4.2.19 on 2025-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_logintable_first_name_logintable_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isblocked',
            field=models.BooleanField(default=False),
        ),
    ]
